// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://dkbumxunrjvsuwrtqcyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYnVteHVucmp2c3V3cnRxY3lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTI4NjUsImV4cCI6MjA2ODkyODg2NX0.KlHz-go9JV19WgCbOyRuQJdcZ5DQ8P3VinwRamC9bcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  },
});

// Debug logging
console.log('Supabase client initialized with:', {
  url: SUPABASE_URL,
  keyLength: SUPABASE_PUBLISHABLE_KEY?.length || 0,
  keyPrefix: SUPABASE_PUBLISHABLE_KEY?.substring(0, 20) + '...'
});